tools:
    php_code_coverage:
        test_command: "phpunit -c tests/"
    php_sim: true
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["src/*"]
    php_analyzer: true
